novari:
  org-id: fintlabs.no
  application-id: fint-kontroll-device-factory
  cache:
    defaultCacheEntryTimeToLive: 518400000
    defaultCacheHeapSize: 1000000
  kafka:
    topic:
      org-id: fintlabs-no
      domain-context: kontroll
    application-id: fintlabs.no
    default-replicas: 1
  kontroll:
    publishing:
      initial-delay: 3000
      fixed-delay: 9000
      membership-initial-delay: 6000
    status:
      active: ["3","4"]
      inactive: ["1","2"]
      deleted: []
spring:
  kafka:
    consumer:
      group-id: fint-kontroll-device-factory
logging:
  level:
    root: INFO
    org.apache.kafka: INFO
    no.novari.cache.ehcache.FintEhCacheEventLogger: WARN