apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-device-factory
  app.kubernetes.io/instance: fint-kontroll-device-factory_fintlabs_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fintlabs.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "fintlabs.no"
      - op: add
        path: "/spec/resources"
        value:
          limits:
            memory: "5000Mi"
          requests:
            cpu: "500m"
            memory: "1500Mi"
      - op: replace
        path: "/spec/env/2/value"
        value: "300000"
      - op: replace
        path: "/spec/env/3/value"
        value: "43200000"
      - op: replace
        path: "/spec/env/1/value"
        value: "fintlabs-no-fint-kontroll-device-factory"
      - op: replace
        path: "/spec/env/6/value"
        value: [ '3','4' ]
      - op: replace
        path: "/spec/env/7/value"
        value: [ '1','2' ]
      - op: replace
        path: "/spec/env/8/value"
        value: [ ]
    target:
      kind: Application
      name: fint-kontroll-device-factory





