apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bfk-no
resources:
  - ../../../base
labels:
  - pairs:
      app.kubernetes.io/name: fint-kontroll-device-factory
      app.kubernetes.io/instance: fint-kontroll-device-factory_bfk_no
      app.kubernetes.io/version: latest
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: fint-kontroll
      fintlabs.no/team: bas
      fintlabs.no/org-id: bfk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "bfk.no"
      - op: add
        path: "/spec/resources"
        value:
          limits:
            memory: "5000Mi"
          requests:
            cpu: "500m"
            memory: "1500Mi"
      - op: replace
        path: "/spec/env/1/value"
        value: "bfk-no-fint-kontroll-device-factory"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "bfk-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "bfk-no.kontroll.*"
      - op: add
        path: "/spec/env/-"
        value:
          name: "novari.kafka.topic.orgId"
          value: "bfk-no"
    target:
      kind: Application
      name: fint-kontroll-device-factory

