apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-device-factory
  app.kubernetes.io/instance: fint-kontroll-device-factory_nfk_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: nfk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "nfk.no"
      - op: add
        path: "/spec/resources"
        value:
          limits:
            memory: "5000Mi"
          requests:
            cpu: "500m"
            memory: "1500Mi"
      - op: replace
        path: "/spec/env/1/value"
        value: "nfk-no-fint-kontroll-device-factory"
      - op: replace
        path: "/spec/env/2/value"
        value: "0 0/3 * * * ?"
      - op: replace
        path: "/spec/env/3/value"
        value: "0 0/3 * * * ?"
      - op: replace
        path: "/spec/env/4/value"
        value: "0 0/3 * * * ?"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "nfk-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "nfk-no.kontroll.*"
    target:
      kind: Application
      name: fint-kontroll-device-factory

